name: Deploy to Fly.io

on:
  push:
    branches:
      - main
    paths:
      - 'Threads_exercises/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          cd Threads_exercises
          flyctl deploy --remote-only
          
      - name: Deployment Status
        run: echo "✅ Deployed successfully to Fly.io!"
