name: Deploy to Render

on:
  push:
    branches:
      - main
    paths:
      - 'Threads_exercises/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger Render Deploy
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl -X POST "$RENDER_DEPLOY_HOOK_URL"
          
      - name: Deployment Status
        run: echo "✅ Deployment triggered on Render!"
